function sendMessage() {
  const userInput = document.getElementById("user-input").value;
  const outputBox = document.getElementById("chat-output");

  const reply = getReply(userInput);
  outputBox.innerText = reply;

  // Đọc bằng giọng nói
  speak(reply);
}

function getReply(input) {
  input = input.toLowerCase();

  if (input.includes("chào")) return "Chào bạn! Mình có thể giúp gì hôm nay?";
  if (input.includes("thái nguyên")) return "Thái Nguyên nổi tiếng với chè Tân Cương và Hồ Núi Cốc!";
  if (input.includes("chè tân cương")) return "Chè Tân Cương là đặc sản nổi bật nhất của Thái Nguyên.";
  if (input.includes("hồ núi cốc")) return "Hồ Núi Cốc là điểm du lịch sinh thái nổi bật của Thái Nguyên.";
  if (input.includes("đặc sản")) return "Ngoài chè, Thái Nguyên còn có bánh chưng Bờ Đậu, tương nếp Úc Kỳ.";
  if (input.includes("lễ hội")) return "Thái Nguyên có lễ hội Lồng Tồng, lễ hội Cầu Mùa, rất đặc sắc.";
  if (input.includes("khí hậu")) return "Khí hậu Thái Nguyên mang đặc trưng nhiệt đới gió mùa, mát mẻ quanh năm.";
  if (input.includes("giáo dục")) return "Đại học Thái Nguyên là trung tâm giáo dục lớn tại miền Bắc.";
  if (input.includes("khu công nghiệp")) return "Thái Nguyên có nhiều khu công nghiệp như Samsung, Sông Công.";
  if (input.includes("lịch sử")) return "Thái Nguyên từng là chiến khu Việt Bắc, đóng vai trò lớn trong kháng chiến.";
  if (input.includes("chè tân cương")) return "Chè Tân Cương là đặc sản nổi bật của Thái Nguyên, nổi tiếng với hương vị thơm ngon, đậm đà.";
  if (input.includes("bánh chưng bờ đậu")) return "Bánh chưng Bờ Đậu là món ăn đặc sản của Thái Nguyên, được làm từ gạo nếp, thịt lợn và đậu xanh.";
  if (input.includes("tương nếp úc kỳ")) return "Tương nếp Úc Kỳ là một loại tương đặc sản của Thái Nguyên, được chế biến từ đậu nành lên men.";
  if (input.includes("món ăn đặc sản thái nguyên")) return "Ngoài chè Tân Cương, Thái Nguyên còn có bánh chưng Bờ Đậu, tương nếp Úc Kỳ, và gà đồi đặc biệt.";
  if (input.includes("gà đồi thái nguyên")) return "Gà đồi Thái Nguyên nổi tiếng với thịt săn chắc, thơm ngon, được nuôi thả tự nhiên.";
  if (input.includes("bánh khảo")) return "Bánh khảo là một món ăn vặt phổ biến ở Thái Nguyên, được làm từ gạo nếp, vừng và mật ong.";
  if (input.includes("xôi ngũ sắc")) return "Xôi ngũ sắc là món ăn truyền thống của Thái Nguyên, có màu sắc đẹp mắt và hương vị đặc biệt.";
  if (input.includes("bánh cuốn thái nguyên")) return "Bánh cuốn Thái Nguyên có phần nhân thịt, hành phi và được ăn kèm với nước mắm chua ngọt.";
  if (input.includes("cơm lam thái nguyên")) return "Cơm lam Thái Nguyên là món ăn truyền thống, gạo được nấu trong ống tre, có hương vị đặc trưng.";
  if (input.includes("canh măng thái nguyên")) return "Canh măng là món ăn quen thuộc trong bữa cơm của người Thái Nguyên, được làm từ măng tươi và thịt.";
  if (input.includes("thái nguyên")) return "Thái Nguyên là tỉnh ở miền Bắc Việt Nam, nổi tiếng với những đồi chè xanh bạt ngàn và khí hậu mát mẻ.";
  if (input.includes("thái nguyên")) return "Thái Nguyên là tỉnh ở miền Bắc Việt Nam, nổi tiếng với những đồi chè xanh bạt ngàn và khí hậu mát mẻ.";
  if (input.includes("thác mưa")) return "Thác Mưa, nằm trong khu bảo tồn thiên nhiên Thái Nguyên, có dòng nước trong xanh và khung cảnh hoang sơ.";
  if (input.includes("vườn quốc gia ba bể")) return "Vườn quốc gia Ba Bể nằm ở Thái Nguyên, là một khu sinh thái tuyệt vời với hồ Ba Bể rộng lớn và rừng nguyên sinh.";
  if (input.includes("hồ sinh thái tân cương")) return "Hồ sinh thái Tân Cương ở Thái Nguyên là một nơi lý tưởng để thư giãn và ngắm cảnh thiên nhiên thơ mộng.";
  if (input.includes("khu bảo tồn thiên nhiên kẻ gỗ")) return "Khu bảo tồn thiên nhiên Kẻ Gỗ có cảnh đẹp hoang sơ, rất thích hợp cho những ai yêu thiên nhiên.";
  if (input.includes("công viên cây xanh thái nguyên")) return "Công viên cây xanh Thái Nguyên là một địa điểm lý tưởng để dạo chơi và thư giãn giữa thiên nhiên xanh mát.";
  if (input.includes("thung lũng chè tân cương")) return "Thung lũng chè Tân Cương có đồi chè bạt ngàn, là một trong những địa điểm du lịch nổi tiếng của Thái Nguyên.";
  if (input.includes("đảo ngọc bắc vân")) return "Đảo Ngọc Bắc Vân nằm trên hồ Ba Bể, có phong cảnh rất thơ mộng và không khí trong lành.";
  if (input.includes("cánh đồng chè thái nguyên")) return "Cánh đồng chè ở Thái Nguyên rộng lớn, là nơi trồng chè Tân Cương nổi tiếng và là điểm tham quan lý tưởng.";
  if (input.includes("khu sinh thái hồ núi cốc")) return "Khu sinh thái Hồ Núi Cốc có không gian thư giãn tuyệt vời, là nơi lý tưởng cho các hoạt động dã ngoại.";
  if (input.includes("hồ gươm thái nguyên")) return "Hồ Gươm ở Thái Nguyên có khung cảnh bình yên và không khí trong lành.";
  if (input.includes("địa điểm du lịch thài nguyên")) return "Thái Nguyên có nhiều điểm du lịch nổi tiếng như Hồ Núi Cốc, Chùa Vân Sơn, Thác Mưa, và Vườn Quốc Gia Ba Bể.";
  if (input.includes("địa điểm du lịch thài nguyên")) return "Thái Nguyên có nhiều điểm du lịch nổi tiếng như Hồ Núi Cốc, Chùa Vân Sơn, Thác Mưa, và Vườn Quốc Gia Ba Bể.";
  if (input.includes("chùa đình lâm")) return "Chùa Đình Lâm là một trong những ngôi chùa linh thiêng của Thái Nguyên, có không gian thanh tịnh và cảnh vật yên bình.";
  if (input.includes("khu du lịch sinh thái tân cương")) return "Khu du lịch sinh thái Tân Cương nổi tiếng với phong cảnh núi rừng hoang sơ, là địa điểm lý tưởng để thư giãn.";
  if (input.includes("chùa vân sơn thái nguyên")) return "Chùa Vân Sơn là nơi thờ Phật linh thiêng, tọa lạc trên núi Đại Vân với cảnh quan thiên nhiên tươi đẹp.";
  if (input.includes("hồ núi cốc thài nguyên")) return "Hồ Núi Cốc là điểm du lịch sinh thái nổi tiếng, với hồ nước rộng lớn và không gian yên bình.";
  if (input.includes("địa điểm du lịch sinh thái")) return "Thái Nguyên có nhiều khu du lịch sinh thái như Hồ Núi Cốc, Vườn Quốc Gia Ba Bể, và Thác Mưa.";
  if (input.includes("hồ ba bể thài nguyên")) return "Hồ Ba Bể có vẻ đẹp tự nhiên tuyệt vời, thích hợp cho các hoạt động du lịch sinh thái và dã ngoại.";
  if (input.includes("thung lũng tân cương")) return "Thung lũng Tân Cương là nơi nổi tiếng với cảnh sắc thiên nhiên đẹp và chè Tân Cương đặc sản.";
  if (input.includes("khu du lịch mỏ gà")) return "Khu du lịch Mỏ Gà có những ngọn núi hùng vĩ, và là điểm đến yêu thích của những người đam mê khám phá.";
  if (input.includes("khu du lịch sinh thái ba bể")) return "Khu du lịch sinh thái Ba Bể là điểm đến lý tưởng cho những ai yêu thiên nhiên và muốn trải nghiệm không gian hoang sơ.";
  if (input.includes("đi đến hồ núi cốc")) return "Để đến Hồ Núi Cốc, bạn có thể đi từ trung tâm thành phố Thái Nguyên, qua quốc lộ 3, sau đó rẽ vào đường dẫn đến hồ.";
  if (input.includes("đi đến chùa vân sơn")) return "Để đến Chùa Vân Sơn, bạn di chuyển theo hướng quốc lộ 37 từ trung tâm thành phố Thái Nguyên, sau đó lên núi Đại Vân.";
  if (input.includes("đi đến thác mưa")) return "Thác Mưa nằm ở khu bảo tồn thiên nhiên, bạn có thể đi theo quốc lộ 3 rồi rẽ vào đường mòn dẫn đến thác.";
  if (input.includes("đi đến thung lũng tân cương")) return "Thung lũng Tân Cương nằm cách trung tâm thành phố Thái Nguyên khoảng 20km, bạn đi theo quốc lộ 3, rồi rẽ vào đường dẫn vào thung lũng.";
  if (input.includes("đi đến vườn quốc gia ba bể")) return "Vườn quốc gia Ba Bể cách Thái Nguyên khoảng 80km, bạn di chuyển theo quốc lộ 3, rồi rẽ vào đường dẫn tới vườn quốc gia.";
  if (input.includes("đi đến hồ ba bể")) return "Hồ Ba Bể cách thành phố Thái Nguyên khoảng 100km, bạn di chuyển theo quốc lộ 3 và rẽ vào đường tỉnh lộ.";
  if (input.includes("đi đến khu du lịch sinh thái tân cương")) return "Khu du lịch sinh thái Tân Cương cách trung tâm thành phố khoảng 25km, bạn đi theo quốc lộ 3, rồi rẽ vào đường dẫn đến khu du lịch.";
  if (input.includes("đi đến khu du lịch mỏ gà")) return "Khu du lịch Mỏ Gà cách trung tâm thành phố khoảng 30km, bạn di chuyển theo quốc lộ 37 và rẽ vào đường mòn.";
  if (input.includes("đi đến chùa đình lâm")) return "Chùa Đình Lâm nằm ở huyện Phú Lương, cách trung tâm thành phố khoảng 40km, bạn đi theo quốc lộ 3 rồi rẽ vào đường mòn.";
  if (input.includes("đi đến chùa bách luân")) return "Chùa Bách Luân nằm tại huyện Phú Lương, cách thành phố Thái Nguyên khoảng 30km, bạn đi theo quốc lộ 3.";
  if (input.includes("lịch sử thái nguyên")) return "Thái Nguyên là mảnh đất lịch sử, nơi diễn ra nhiều sự kiện quan trọng trong kháng chiến chống Pháp và Mỹ.";
  if (input.includes("chiến khu việt bắc")) return "Chiến khu Việt Bắc là căn cứ kháng chiến trong kháng chiến chống Pháp, Thái Nguyên là một phần của khu vực này.";
  if (input.includes("thái nguyên trong chiến tranh")) return "Thái Nguyên đóng vai trò quan trọng trong các cuộc kháng chiến, là nơi tập trung quân đội và quân dân.";
  if (input.includes("chiến tranh việt nam")) return "Trong chiến tranh Việt Nam, Thái Nguyên là một trong những nơi quan trọng trong chiến lược chống Mỹ.";
  if (input.includes("thái nguyên kháng chiến")) return "Thái Nguyên là nơi diễn ra nhiều chiến dịch quan trọng trong kháng chiến chống Pháp và chống Mỹ.";
  if (input.includes("sự kiện lịch sử thái nguyên")) return "Thái Nguyên là nơi diễn ra nhiều sự kiện lịch sử quan trọng, đặc biệt trong hai cuộc kháng chiến.";
  if (input.includes("cách mạng tháng 8 tại thái nguyên")) return "Cách mạng Tháng 8 ở Thái Nguyên đã diễn ra với sự tham gia mạnh mẽ của quân dân Thái Nguyên.";
  if (input.includes("di tích lịch sử thái nguyên")) return "Thái Nguyên có nhiều di tích lịch sử, nổi bật là di tích chiến khu Việt Bắc và các địa danh gắn với kháng chiến.";
  if (input.includes("kháng chiến chống pháp")) return "Thái Nguyên là nơi diễn ra nhiều trận chiến lớn trong kháng chiến chống Pháp, đặc biệt là trong chiến dịch Việt Bắc.";
  if (input.includes("kháng chiến chống pháp")) return "Thái Nguyên là nơi diễn ra nhiều trận chiến lớn trong kháng chiến chống Pháp, đặc biệt là trong chiến dịch Việt Bắc.";
  if (input.includes("chiến thắng thái nguyên")) return "Chiến thắng Thái Nguyên trong kháng chiến chống Pháp là một chiến thắng quan trọng, đánh dấu bước ngoặt trong lịch sử.";
  if (input.includes("sự kiện tháng 8 năm 1945 thái nguyên")) return "Cách mạng Tháng 8 năm 1945 tại Thái Nguyên là một sự kiện lịch sử quan trọng, đánh dấu sự kiện khởi đầu của cuộc kháng chiến chống thực dân Pháp.";
  if (input.includes("chiến khu việt bắc thái nguyên")) return "Chiến khu Việt Bắc là nơi đóng vai trò quan trọng trong kháng chiến chống Pháp và Mỹ, Thái Nguyên là một phần không thể thiếu của chiến khu này.";
  if (input.includes("địa danh lịch sử thái nguyên")) return "Các địa danh lịch sử nổi bật của Thái Nguyên gồm có đồn Phú Lương, khu di tích chiến khu Việt Bắc và các địa điểm liên quan đến chiến tranh.";
  if (input.includes("di tích chiến khu việt bắc")) return "Di tích chiến khu Việt Bắc tại Thái Nguyên là một trong những khu di tích lịch sử quan trọng, ghi dấu những chiến công trong kháng chiến chống Pháp.";
  if (input.includes("bảo tàng thái nguyên")) return "Bảo tàng Thái Nguyên trưng bày nhiều hiện vật quý giá về lịch sử và văn hóa của tỉnh này.";
  if (input.includes("cuộc khởi nghĩa thái nguyên")) return "Cuộc khởi nghĩa ở Thái Nguyên diễn ra vào những năm đầu thế kỷ 20, đánh dấu sự đấu tranh chống thực dân Pháp.";
  if (input.includes("tượng đài chiến thắng thái nguyên")) return "Tượng đài chiến thắng Thái Nguyên được xây dựng để tưởng nhớ chiến thắng trong các cuộc kháng chiến chống thực dân Pháp và đế quốc Mỹ.";
  if (input.includes("chiến trường thái nguyên")) return "Thái Nguyên là một trong những chiến trường quan trọng trong kháng chiến, nơi diễn ra nhiều trận đánh lớn với sự tham gia của quân dân Việt Nam.";
  if (input.includes("cá suối thái nguyên")) return "Cá suối ở Thái Nguyên có hương vị thơm ngon, thịt chắc, thường được chế biến thành các món nướng hoặc kho.";
  if (input.includes("bánh chưng bờ đậu")) return "Bánh chưng Bờ Đậu là món ăn truyền thống đặc biệt của Thái Nguyên, mang đậm nét văn hóa của người dân nơi đây.";
  if (input.includes("món ăn chế biến từ chè")) return "Tại Thái Nguyên, chè không chỉ được thưởng thức dưới dạng trà mà còn được chế biến thành các món ăn độc đáo như chè sữa, chè đậu.";
  if (input.includes("bánh tôm thái nguyên")) return "Bánh tôm Thái Nguyên là món ăn ngon, thường được làm từ tôm tươi và bột gạo, ăn kèm với nước mắm chua ngọt.";
  if (input.includes("xôi ngũ sắc thái nguyên")) return "Xôi ngũ sắc là món ăn đặc trưng của Thái Nguyên, có nhiều màu sắc hấp dẫn và là món ăn truyền thống trong các dịp lễ hội.";
  if (input.includes("bánh dày thái nguyên")) return "Bánh dày Thái Nguyên có hương vị mềm dẻo, thơm ngon, được làm từ gạo nếp và thường được ăn kèm với muối vừng.";
  if (input.includes("canh chua thái nguyên")) return "Canh chua Thái Nguyên được làm từ các loại cá tươi và rau thơm, có vị chua nhẹ và đậm đà.";
  if (input.includes("gà đồi thái nguyên")) return "Gà đồi Thái Nguyên nổi tiếng với thịt săn chắc, thơm ngon, được nuôi thả tự nhiên, là món ăn không thể bỏ qua khi đến Thái Nguyên.";
  if (input.includes("mứt dừa thái nguyên")) return "Mứt dừa Thái Nguyên là món ăn vặt nổi tiếng, có hương vị ngọt ngào và thơm nức.";
  if (input.includes("tương nếp thái nguyên")) return "Tương nếp là gia vị đặc biệt của Thái Nguyên, được làm từ đậu nành lên men, dùng để ăn kèm với các món ăn truyền thống.";
  if (input.includes("chè thái nguyên")) return "Chè Tân Cương nổi tiếng của Thái Nguyên có hương vị thơm ngon, đậm đà, được sản xuất từ những cây chè cổ thụ tại địa phương.";
  if (input.includes("bánh cuốn thái nguyên")) return "Bánh cuốn Thái Nguyên có vỏ mềm mịn, nhân thịt thơm ngon, ăn kèm với nước mắm chua ngọt, đặc biệt.";
  if (input.includes("món ăn từ gạo nếp thái nguyên")) return "Thái Nguyên có nhiều món ăn chế biến từ gạo nếp, như xôi ngũ sắc, xôi lạc, và các món xôi đặc trưng khác.";
  if (input.includes("bánh trôi thái nguyên")) return "Bánh trôi Thái Nguyên là một món ăn đặc trưng, với lớp vỏ mềm, nhân đậu xanh và nước đường thơm ngọt.";
  if (input.includes("cơm lam thái nguyên")) return "Cơm lam Thái Nguyên được làm từ gạo nếp và nướng trong ống tre, có hương vị rất đặc biệt.";
  if (input.includes("bánh mỳ kẹp thái nguyên")) return "Bánh mỳ kẹp Thái Nguyên là món ăn sáng phổ biến, với những miếng thịt nướng thơm ngon, rau sống và gia vị đặc biệt.";
  if (input.includes("canh rau thái nguyên")) return "Canh rau Thái Nguyên được làm từ những loại rau đặc trưng của vùng núi, có hương vị thanh mát, bổ dưỡng.";
  if (input.includes("chả giò thái nguyên")) return "Chả giò Thái Nguyên là món ăn nổi tiếng, với lớp vỏ giòn rụm, nhân thịt và rau củ tươi ngon.";
  if (input.includes("bánh đậu xanh thái nguyên")) return "Bánh đậu xanh Thái Nguyên là món ăn vặt truyền thống, có vị ngọt thanh, thơm ngon và rất đặc trưng.";
  if (input.includes("nước chè thái nguyên")) return "Nước chè Thái Nguyên, đặc biệt là chè Tân Cương, nổi tiếng khắp cả nước vì hương vị thơm ngon, đậm đà.";
  if (input.includes("hồ núi cốc")) return "Hồ Núi Cốc là một trong những điểm du lịch nổi tiếng của Thái Nguyên, với cảnh quan thiên nhiên tuyệt đẹp và các hoạt động vui chơi giải trí.";
  if (input.includes("vườn quốc gia ba bể")) return "Vườn Quốc gia Ba Bể là khu bảo tồn thiên nhiên đặc biệt, nơi có hồ nước trong xanh và hệ sinh thái phong phú.";
  if (input.includes("chùa vân sơn thái nguyên")) return "Chùa Vân Sơn là một ngôi chùa cổ kính, nổi tiếng với không gian thanh tịnh và cảnh quan hữu tình.";
  if (input.includes("thung lũng tân cương")) return "Thung lũng Tân Cương là một trong những điểm du lịch đẹp của Thái Nguyên, nơi sản xuất chè Tân Cương nổi tiếng.";
  if (input.includes("hồ ba bể từ thái nguyên")) return "Hồ Ba Bể cách Thái Nguyên khoảng 100 km, có thể đi bằng xe khách hoặc xe tự lái.";
  if (input.includes("chùa bách luân")) return "Chùa Bách Luân là ngôi chùa nổi tiếng ở Thái Nguyên, là điểm đến tâm linh được nhiều du khách yêu thích.";
  if (input.includes("khu di tích chiến khu việt bắc")) return "Khu di tích chiến khu Việt Bắc tại Thái Nguyên là nơi lưu giữ nhiều dấu ấn lịch sử quan trọng trong kháng chiến chống Pháp.";
  if (input.includes("đền thác vàng thái nguyên")) return "Đền Thác Vàng nằm tại xã Tân Cương, Thái Nguyên, là một trong những địa danh nổi bật với vẻ đẹp tự nhiên và kiến trúc độc đáo.";
  if (input.includes("điểm du lịch thái nguyên nổi tiếng")) return "Thái Nguyên có nhiều điểm du lịch nổi tiếng như Hồ Núi Cốc, Vườn Quốc Gia Ba Bể, Thung Lũng Tân Cương, và Chùa Vân Sơn.";
  if (input.includes("hồ núi cốc cách thái nguyên bao xa")) return "Hồ Núi Cốc cách trung tâm thành phố Thái Nguyên khoảng 20 km, bạn có thể dễ dàng di chuyển bằng xe ô tô.";
  if (input.includes("cách mạng tháng 8 1945 thái nguyên")) return "Cách mạng tháng 8 năm 1945 tại Thái Nguyên là một trong những dấu mốc quan trọng, góp phần vào sự thành công của cách mạng cả nước.";
  if (input.includes("thái nguyên trong chiến tranh việt nam")) return "Trong chiến tranh Việt Nam, Thái Nguyên là nơi đóng vai trò chiến lược quan trọng, là hậu phương vững chắc cho cuộc kháng chiến.";
  if (input.includes("tưởng niệm các anh hùng thái nguyên")) return "Thái Nguyên có nhiều đài tưởng niệm các anh hùng liệt sĩ, là nơi để tri ân những người đã hy sinh cho độc lập tự do của đất nước.";
  if (input.includes("đoàn kết thái nguyên trong chiến tranh")) return "Trong chiến tranh, nhân dân Thái Nguyên đã thể hiện sự đoàn kết, quyết tâm chiến đấu chống lại các thế lực xâm lược.";
  if (input.includes("di tích lịch sử thái nguyên")) return "Các di tích lịch sử nổi tiếng của Thái Nguyên bao gồm khu di tích chiến khu Việt Bắc, Đền Thác Vàng, và Đình Lâm Sơn.";
  if (input.includes("chiến khu việt bắc và thái nguyên")) return "Chiến khu Việt Bắc, trong đó có Thái Nguyên, là căn cứ quan trọng của quân đội Việt Nam trong kháng chiến chống Pháp.";
  if (input.includes("kháng chiến chống mỹ thái nguyên")) return "Trong kháng chiến chống Mỹ, Thái Nguyên là một trong những tỉnh miền Bắc đóng vai trò quan trọng trong chiến lược bảo vệ tổ quốc.";
  if (input.includes("người lính thái nguyên")) return "Người lính Thái Nguyên là biểu tượng của sự kiên cường, dũng cảm trong cuộc kháng chiến chống ngoại xâm.";
  if (input.includes("mặt trận việt bắc thái nguyên")) return "Mặt trận Việt Bắc là nơi diễn ra nhiều trận đánh lớn, Thái Nguyên đóng vai trò quan trọng trong chiến dịch này.";
  if (input.includes("hành trình chiến thắng tại thái nguyên")) return "Các chiến thắng tại Thái Nguyên trong lịch sử đã giúp củng cố tinh thần kháng chiến và khẳng định ý chí chiến đấu của nhân dân.";
  if (input.includes("chè thái nguyên")) return "Chè Tân Cương nổi tiếng của Thái Nguyên có hương vị thơm ngon, đậm đà, được sản xuất từ những cây chè cổ thụ tại địa phương.";
  if (input.includes("bánh cuốn thái nguyên")) return "Bánh cuốn Thái Nguyên có vỏ mềm mịn, nhân thịt thơm ngon, ăn kèm với nước mắm chua ngọt, đặc biệt.";
  if (input.includes("món ăn từ gạo nếp thái nguyên")) return "Thái Nguyên có nhiều món ăn chế biến từ gạo nếp, như xôi ngũ sắc, xôi lạc, và các món xôi đặc trưng khác.";
  if (input.includes("bánh trôi thái nguyên")) return "Bánh trôi Thái Nguyên là một món ăn đặc trưng, với lớp vỏ mềm, nhân đậu xanh và nước đường thơm ngọt.";
  if (input.includes("cơm lam thái nguyên")) return "Cơm lam Thái Nguyên được làm từ gạo nếp và nướng trong ống tre, có hương vị rất đặc biệt.";
  if (input.includes("bánh mỳ kẹp thái nguyên")) return "Bánh mỳ kẹp Thái Nguyên là món ăn sáng phổ biến, với những miếng thịt nướng thơm ngon, rau sống và gia vị đặc biệt.";
  if (input.includes("canh rau thái nguyên")) return "Canh rau Thái Nguyên được làm từ những loại rau đặc trưng của vùng núi, có hương vị thanh mát, bổ dưỡng.";
  if (input.includes("chả giò thái nguyên")) return "Chả giò Thái Nguyên là món ăn nổi tiếng, với lớp vỏ giòn rụm, nhân thịt và rau củ tươi ngon.";
  if (input.includes("bánh đậu xanh thái nguyên")) return "Bánh đậu xanh Thái Nguyên là món ăn vặt truyền thống, có vị ngọt thanh, thơm ngon và rất đặc trưng.";
  if (input.includes("nước chè thái nguyên")) return "Nước chè Thái Nguyên, đặc biệt là chè Tân Cương, nổi tiếng khắp cả nước vì hương vị thơm ngon, đậm đà.";
  if (input.includes("văn hóa thái nguyên")) return "Thái Nguyên là nơi có nền văn hóa đặc sắc, với nhiều lễ hội truyền thống như Lễ hội Chùa Vân Sơn, Hội Lim, và các trò chơi dân gian.";
  if (input.includes("nghệ thuật truyền thống thái nguyên")) return "Thái Nguyên nổi tiếng với các môn nghệ thuật truyền thống như hát Xoan, múa rối nước và hát chèo.";
  if (input.includes("lễ hội truyền thống thái nguyên")) return "Các lễ hội truyền thống của Thái Nguyên bao gồm Lễ hội Chùa Vân Sơn, Lễ hội Đình Lâm Sơn, và Lễ hội Tết Nguyên Đán tại nhiều làng xã.";
  if (input.includes("phong tục tập quán thái nguyên")) return "Phong tục tập quán của người dân Thái Nguyên rất phong phú, từ đám cưới, lễ hội đến các nghi thức tôn giáo.";
  if (input.includes("múa rối thái nguyên")) return "Múa rối nước Thái Nguyên là một loại hình nghệ thuật dân gian độc đáo, được gìn giữ và phát huy trong cộng đồng.";
  if (input.includes("hát xoan thái nguyên")) return "Hát Xoan là một loại hình nghệ thuật truyền thống của Thái Nguyên, được UNESCO công nhận là di sản văn hóa phi vật thể.";
  if (input.includes("trò chơi dân gian thái nguyên")) return "Thái Nguyên có nhiều trò chơi dân gian như ném còn, đập niêu, thi nấu cơm, và các trò chơi khác trong lễ hội truyền thống.";
  if (input.includes("di sản văn hóa thái nguyên")) return "Thái Nguyên có nhiều di sản văn hóa nổi bật, bao gồm các di tích lịch sử và các hoạt động văn hóa, nghệ thuật đặc sắc.";
  if (input.includes("người dân thái nguyên")) return "Người dân Thái Nguyên rất mến khách và giữ gìn các giá trị văn hóa truyền thống của dân tộc mình.";
  if (input.includes("ẩm thực văn hóa thái nguyên")) return "Ẩm thực Thái Nguyên rất đa dạng và phong phú, với các món ăn như chè Tân Cương, bánh cuốn, và xôi nếp đặc trưng của vùng này.";
  if (input.includes("đại học thái nguyên")) return "Đại học Thái Nguyên là một trong những cơ sở giáo dục lớn, đào tạo nhiều ngành nghề từ khoa học, kỹ thuật đến nghệ thuật.";
  if (input.includes("trường học tại thái nguyên")) return "Thái Nguyên có nhiều trường học từ cấp tiểu học đến đại học, với cơ sở vật chất và chất lượng giảng dạy ngày càng nâng cao.";
  if (input.includes("khoa học công nghệ thái nguyên")) return "Thái Nguyên là nơi phát triển các ngành khoa học công nghệ, đặc biệt là nghiên cứu về nông nghiệp, môi trường và công nghiệp chế biến.";
  if (input.includes("hệ thống giáo dục thái nguyên")) return "Hệ thống giáo dục ở Thái Nguyên phát triển đồng bộ, với nhiều trường đại học, cao đẳng và các trung tâm đào tạo nghề.";
  if (input.includes("ngành nghề tại thái nguyên")) return "Thái Nguyên có nhiều ngành nghề nổi bật, đặc biệt là sản xuất chè, nông nghiệp, và công nghiệp chế biến thực phẩm.";
  if (input.includes("học bổng tại đại học thái nguyên")) return "Đại học Thái Nguyên cung cấp nhiều học bổng cho sinh viên xuất sắc và các chương trình nghiên cứu khoa học.";
  if (input.includes("nâng cao chất lượng giáo dục thái nguyên")) return "Thái Nguyên đã có nhiều cải cách và nâng cấp trong chất lượng giáo dục, đặc biệt chú trọng đến việc ứng dụng công nghệ trong giảng dạy.";
  if (input.includes("khoa học nghiên cứu tại thái nguyên")) return "Thái Nguyên là nơi có nhiều trung tâm nghiên cứu khoa học, đặc biệt trong các lĩnh vực nông nghiệp, khoa học xã hội và môi trường.";
  if (input.includes("cơ sở đào tạo thái nguyên")) return "Thái Nguyên có nhiều cơ sở đào tạo từ các trường phổ thông đến đại học, giúp nâng cao chất lượng nguồn nhân lực cho khu vực và cả nước.";
  if (input.includes("thực tập khoa học thái nguyên")) return "Các sinh viên tại Thái Nguyên có cơ hội thực tập tại các trung tâm nghiên cứu, các cơ sở sản xuất nông sản, và các doanh nghiệp công nghệ.";
  if (input.includes("bảo vệ môi trường thái nguyên")) return "Thái Nguyên đang nỗ lực bảo vệ môi trường thông qua các chương trình tái chế, giảm thiểu ô nhiễm và bảo vệ hệ sinh thái tự nhiên.";
  if (input.includes("ôn nhiễm không khí thái nguyên")) return "Ô nhiễm không khí tại Thái Nguyên chủ yếu là do các hoạt động công nghiệp và giao thông, nhưng đang được cải thiện với các biện pháp kiểm soát.";
  if (input.includes("chương trình bảo vệ môi trường thái nguyên")) return "Thái Nguyên triển khai nhiều chương trình bảo vệ môi trường như trồng cây xanh, giảm thiểu rác thải nhựa và phát triển năng lượng tái tạo.";
  if (input.includes("nước sạch thái nguyên")) return "Thái Nguyên đã triển khai các dự án cung cấp nước sạch cho cộng đồng, đặc biệt là vùng sâu, vùng xa, để nâng cao chất lượng cuộc sống.";
  if (input.includes("quản lý rác thải thái nguyên")) return "Thái Nguyên đã áp dụng các biện pháp quản lý rác thải hiệu quả, bao gồm phân loại rác và tái chế tại các khu dân cư và các khu công nghiệp.";
  if (input.includes("sản phẩm tái chế thái nguyên")) return "Thái Nguyên đang thúc đẩy việc sử dụng các sản phẩm tái chế và giảm thiểu việc sử dụng nhựa trong các hoạt động sản xuất và tiêu dùng.";
  if (input.includes("biến đổi khí hậu thái nguyên")) return "Biến đổi khí hậu là một thách thức lớn đối với Thái Nguyên, với nhiệt độ ngày càng cao và mùa mưa kéo dài, ảnh hưởng đến sản xuất nông nghiệp.";
  if (input.includes("bảo vệ đa dạng sinh học thái nguyên")) return "Thái Nguyên có các khu bảo tồn thiên nhiên và các biện pháp bảo vệ động thực vật hoang dã, duy trì sự đa dạng sinh học của vùng đất này.";
  if (input.includes("nghị quyết môi trường thái nguyên")) return "Thái Nguyên thực hiện các nghị quyết về bảo vệ môi trường, tăng cường công tác kiểm tra và xử lý các hành vi gây ô nhiễm.";
  if (input.includes("công viên sinh thái thái nguyên")) return "Thái Nguyên có một số công viên sinh thái, nơi du khách có thể khám phá hệ sinh thái phong phú, rừng núi và thảm thực vật đặc trưng.";
  if (input.includes("kinh tế thái nguyên")) return "Kinh tế Thái Nguyên chủ yếu dựa vào nông nghiệp, đặc biệt là trồng chè, công nghiệp chế biến thực phẩm và khai khoáng.";
  if (input.includes("ngành nông nghiệp thái nguyên")) return "Nông nghiệp Thái Nguyên phát triển mạnh, đặc biệt là trồng chè Tân Cương, cây lúa, và các loại cây ăn quả.";
  if (input.includes("chế biến chè tại thái nguyên")) return "Thái Nguyên nổi tiếng với việc chế biến chè Tân Cương, một trong những sản phẩm xuất khẩu nổi bật của địa phương.";
  if (input.includes("công nghiệp tại thái nguyên")) return "Thái Nguyên có nhiều khu công nghiệp, đặc biệt là các khu chế biến nông sản, sản xuất chế phẩm từ chè và các sản phẩm tiêu dùng khác.";
  if (input.includes("đầu tư kinh tế thái nguyên")) return "Thái Nguyên thu hút đầu tư trong các ngành chế biến nông sản, công nghiệp chế biến thực phẩm và các lĩnh vực dịch vụ du lịch.";
  if (input.includes("mô hình sản xuất nông nghiệp thái nguyên")) return "Thái Nguyên áp dụng mô hình nông nghiệp thông minh và hiện đại, đặc biệt là trong việc trồng chè và các sản phẩm nông sản sạch.";
  if (input.includes("du lịch phát triển kinh tế thái nguyên")) return "Du lịch phát triển mạnh mẽ tại Thái Nguyên, đặc biệt với các điểm du lịch như Hồ Núi Cốc, khu di tích chiến khu Việt Bắc và các vườn chè nổi tiếng.";
  if (input.includes("khai thác khoáng sản thái nguyên")) return "Thái Nguyên có các mỏ khoáng sản phong phú, đặc biệt là khai thác than, sắt và các khoáng sản khác phục vụ cho công nghiệp.";
  if (input.includes("thị trường việc làm thái nguyên")) return "Thị trường việc làm ở Thái Nguyên phát triển mạnh với nhu cầu lớn trong các ngành sản xuất, chế biến nông sản, và dịch vụ.";
  if (input.includes("tỷ lệ phát triển kinh tế thái nguyên")) return "Thái Nguyên có tỷ lệ phát triển kinh tế ổn định, nhờ vào sự phát triển của các ngành công nghiệp, nông nghiệp và du lịch.";
  if (input.includes("giao thông thái nguyên")) return "Giao thông ở Thái Nguyên phát triển, với mạng lưới đường bộ liên kết với các tỉnh lân cận, thuận tiện cho việc di chuyển.";
  if (input.includes("các tuyến đường chính thái nguyên")) return "Các tuyến đường chính của Thái Nguyên bao gồm Quốc lộ 3, Quốc lộ 37 và các đường liên huyện kết nối với các tỉnh khác.";
  if (input.includes("di chuyển từ thái nguyên đến hà nội")) return "Từ Thái Nguyên đến Hà Nội, bạn có thể đi bằng xe khách hoặc xe tự lái theo Quốc lộ 3, khoảng 70 km.";
  if (input.includes("tàu hỏa thái nguyên")) return "Thái Nguyên có tuyến đường sắt kết nối với Hà Nội, rất thuận tiện cho những ai muốn di chuyển bằng tàu hỏa.";
  if (input.includes("xe khách từ thái nguyên")) return "Xe khách từ Thái Nguyên đi các tỉnh miền Bắc rất phổ biến, với nhiều tuyến xe đi các thành phố lớn như Hà Nội, Bắc Giang, Hải Phòng.";
  if (input.includes("mạng lưới giao thông thái nguyên")) return "Thái Nguyên có mạng lưới giao thông khá phát triển, bao gồm các tuyến đường bộ, đường sắt và hệ thống xe khách liên tỉnh.";
  if (input.includes("giao thông nông thôn thái nguyên")) return "Giao thông nông thôn Thái Nguyên được cải thiện từng ngày, với các tuyến đường liên xã và giao thông nội bộ ngày càng được nâng cấp.";
  if (input.includes("cầu qua sông thái nguyên")) return "Thái Nguyên có nhiều cầu qua sông, phục vụ cho việc di chuyển giữa các huyện, giúp cải thiện kết nối giao thông.";
  if (input.includes("hệ thống giao thông công cộng thái nguyên")) return "Thái Nguyên hiện đang phát triển hệ thống giao thông công cộng, với các tuyến xe buýt nội thành phục vụ nhu cầu đi lại của người dân.";
  if (input.includes("đường cao tốc thái nguyên")) return "Hiện nay, Thái Nguyên đang có dự án xây dựng đường cao tốc, nhằm kết nối nhanh chóng với các tỉnh thành trong khu vực.";
  if (input.includes("du lịch")) return "Thái Nguyên có nhiều địa điểm du lịch nổi tiếng như Hồ Núi Cốc và làng chè Tân Cương.";
  if (input.includes("che tân cương")) return "Chè Tân Cương là đặc sản nổi tiếng của Thái Nguyên, bạn có thể tham quan vườn chè tại đây.";
  if (input.includes("hồ núi cốc")) return "Hồ Núi Cốc là một trong những điểm du lịch nổi bật ở Thái Nguyên, bạn có thể tham gia các hoạt động vui chơi trên hồ.";
  if (input.includes("thái nguyên")) return "Thái Nguyên là một tỉnh thuộc miền Bắc Việt Nam, nổi tiếng với chè Tân Cương và Hồ Núi Cốc.";
  if (input.includes("các món ăn")) return "Thái Nguyên có các món ăn ngon như bánh chưng, bún chả, chè Tân Cương, và cơm lam.";
  if (input.includes("công viên")) return "Thái Nguyên có các công viên như công viên Trung Tâm và khu du lịch Hồ Núi Cốc.";
  if (input.includes("lễ hội")) return "Thái Nguyên có lễ hội Hội Lim và lễ hội Chùa Vân Sơn rất đặc sắc.";
  if (input.includes("di tích lịch sử")) return "Thái Nguyên có nhiều di tích lịch sử quan trọng như khu di tích chiến khu Việt Bắc.";
  if (input.includes("điểm tham quan")) return "Ngoài Hồ Núi Cốc, Thái Nguyên còn có các điểm tham quan như Chùa Vân Sơn và làng chè Tân Cương.";
  if (input.includes("nơi chơi cho trẻ em")) return "Thái Nguyên có một số khu vui chơi cho trẻ em như công viên Trung Tâm và các khu vui chơi tại Hồ Núi Cốc.";
  if (input.includes("tourism")) return "Thai Nguyen has many famous tourist destinations such as Nui Coc Lake and Tan Cuong Tea Village.";
  if (input.includes("tan cuong tea")) return "Tan Cuong Tea is a famous specialty of Thai Nguyen, you can visit the tea gardens here.";
  if (input.includes("nui coc lake")) return "Nui Coc Lake is one of the prominent tourist destinations in Thai Nguyen, where you can participate in activities on the lake.";
  if (input.includes("thai nguyen")) return "Thai Nguyen is a province in northern Vietnam, famous for Tan Cuong tea and Nui Coc Lake.";
  if (input.includes("food")) return "Thai Nguyen has delicious dishes like banh chung, bun cha, Tan Cuong tea, and com lam.";
  if (input.includes("park")) return "Thai Nguyen has parks like Trung Tam Park and Nui Coc Lake tourist area.";
  if (input.includes("festival")) return "Thai Nguyen has colorful festivals like the Lim Festival and the Van Son Pagoda Festival.";
  if (input.includes("historical sites")) return "Thai Nguyen has many important historical sites like the Viet Bac Resistance Base site.";
  if (input.includes("attractions")) return "In addition to Nui Coc Lake, Thai Nguyen also has attractions like Van Son Pagoda and Tan Cuong Tea Village.";
  if (input.includes("places for kids")) return "Thai Nguyen has several places for children to play, such as Trung Tam Park and playgrounds at Nui Coc Lake.";
  if (input.includes("Where is Thai Nguyen")) return "Thai Nguyen is a province in northern Vietnam, located about 80km north of Hanoi.";
  if (input.includes("What is beautiful in Thai Nguyen")) return "Thai Nguyen is famous for Nui Coc Lake, Van Son Pagoda, and Tan Cuong tea gardens!";
  if (input.includes("tourism in Thai Nguyen")) return "Thai Nguyen has many attractions like Nui Coc Lake, the Viet Bac Resistance Base, and Tan Cuong Tea Villages.";
  if (input.includes("What food is there in Thai Nguyen")) return "In Thai Nguyen, you can enjoy dishes like banh chung, bun cha, com lam, and famous Tan Cuong tea.";
  if (input.includes("How to go to Thai Nguyen")) return "You can travel to Thai Nguyen by bus, coach, or personal car from Hanoi. It takes about 1.5 hours.";
  if (input.includes("Is there an airport")) return "Currently, there is no airport in Thai Nguyen, but you can fly to Hanoi and travel to Thai Nguyen by car.";
  if (input.includes("How far is it from Hanoi to Thai Nguyen")) return "The distance from Hanoi to Thai Nguyen is about 80km, and it takes around 1.5 hours to travel.";
  if (input.includes("Where is Nui Coc Lake")) return "Nui Coc Lake is located in Dai Tu district, about 20km west of Thai Nguyen city.";
  if (input.includes("How to go to Nui Coc Lake")) return "You can travel to Nui Coc Lake from Thai Nguyen city by car or motorbike, which takes about 30 minutes.";
  if (input.includes("Where is Van Son Pagoda")) return "Van Son Pagoda is located on Van Son Mountain, about 15km from the center of Thai Nguyen city.";
  if (input.includes("How to go to Van Son Pagoda")) return "You can go by car to Van Son Mountain and then hike up to visit Van Son Pagoda.";
  if (input.includes("Where is Tan Cuong Tea Village")) return "Tan Cuong Tea Village is located in Tan Cuong commune, Thai Nguyen city, famous for its lush tea hills.";
  if (input.includes("Can I visit Tan Cuong Tea Village")) return "You can definitely visit Tan Cuong Tea Village, where you can also join tea tours and enjoy fresh tea.";
  if (input.includes("Where is Viet Bac Resistance Base")) return "The Viet Bac Resistance Base is located in the mountainous areas of Thai Nguyen and nearby provinces, where many significant battles took place in history.";
  if (input.includes("How is transportation in Thai Nguyen")) return "Thai Nguyen has a well-developed transportation system, with roads connecting it to other provinces and Hanoi.";
  if (input.includes("Is there a taxi")) return "Yes, there are taxi services available in Thai Nguyen for tourists, and you can call a taxi via phone or use ride-hailing apps.";
  if (input.includes("Is there a good restaurant")) return "Thai Nguyen has many good restaurants serving local dishes like Lua Moi Restaurant and Nui Coc Lake Restaurant.";
  if (input.includes("Is there a hotel")) return "Thai Nguyen has a variety of hotels, from budget to high-end, catering to tourists and business travelers.";
  if (input.includes("Is there a place to stay overnight")) return "You can find hotels or guesthouses in Thai Nguyen city and around tourist spots like Nui Coc Lake.";
  if (input.includes("Is there a motorbike rental")) return "Yes, there are motorbike rental services available in Thai Nguyen city and tourist areas.";
  if (input.includes("What other tourist spots are in Thai Nguyen")) return "Besides Nui Coc Lake, Thai Nguyen has many other attractions like historical sites, museums, and ancient pagodas.";
  if (input.includes("What is famous about Thai Nguyen cuisine")) return "Thai Nguyen cuisine is famous for dishes like Tan Cuong tea, banh chung, bun cha, and com lam.";
  if (input.includes("Where is Tan Cuong Tea famous")) return "Tan Cuong Tea is famous in Dai Tu district and surrounding areas of Tan Cuong, known for its lush tea gardens.";
  if (input.includes("Where can I enjoy Tan Cuong Tea")) return "You can enjoy Tan Cuong Tea in many tea shops or at Tan Cuong Tea Village in Thai Nguyen.";
  if (input.includes("Is there a park")) return "Yes, Thai Nguyen has parks like Trung Tam Park and Nui Coc Lake tourism area.";
  if (input.includes("What is there to do in Thai Nguyen")) return "In Thai Nguyen, you can visit attractions like Nui Coc Lake, Van Son Pagoda, and participate in outdoor activities like hiking and exploring tea villages.";
  if (input.includes("Is there a place for kids to play")) return "Yes, Thai Nguyen has parks and playgrounds for children, including Trung Tam Park and the Nui Coc Lake area.";
  if (input.includes("What is interesting about Nui Coc Lake")) return "Nui Coc Lake has beautiful scenery, and you can enjoy activities like boating, island hopping, or amusement rides at the tourism area.";
  if (input.includes("What festivals are there in Thai Nguyen")) return "Thai Nguyen hosts many festivals, including the Van Son Pagoda Festival, Lim Festival, and other traditional events.";
  if (input.includes("When is the Van Son Pagoda Festival")) return "The Van Son Pagoda Festival is usually held at the beginning of the year, attracting many visitors and locals.";
  if (input.includes("When is the Lim Festival in Thai Nguyen")) return "The Lim Festival is held in January and is one of the largest festivals in the region.";
  if (input.includes("Can I go boating on Nui Coc Lake")) return "Yes, you can rent a boat to explore Nui Coc Lake and visit the small islands in the lake.";
  if (input.includes("What is interesting about Van Son Pagoda")) return "Van Son Pagoda is not only a spiritual destination but also offers stunning views of the surrounding area.";
  if (input.includes("Is there a guide service")) return "Yes, you can hire a local guide at popular tourist destinations like Nui Coc Lake and Viet Bac Resistance Base.";
  if (input.includes("Can I camp in Thai Nguyen")) return "Yes, Thai Nguyen has many areas suitable for camping, especially around Nui Coc Lake and the surrounding mountains.";
  if (input.includes("Is there a gym")) return "Some hotels in Thai Nguyen offer gym facilities for tourists and locals.";
  if (input.includes("Where can I buy souvenirs")) return "You can buy souvenirs at markets or shops in tourist areas like Nui Coc Lake or Tan Cuong Tea Villages.";
  if (input.includes("Is there a supermarket in Thai Nguyen")) return "Yes, Thai Nguyen has several supermarkets like Coopmart, Big C, and smaller local stores.";
  if (input.includes("Is there a place to park")) return "Major tourist spots in Thai Nguyen, like Nui Coc Lake and Van Son Pagoda, have parking areas.";
  if (input.includes("Is there a church")) return "Yes, Thai Nguyen has several churches, including the Thai Nguyen Cathedral, where religious ceremonies are held for the local Catholic community.";
  if (input.includes("Is there a coffee shop")) return "Thai Nguyen has many coffee shops, ranging from casual cafes to upscale ones where you can relax and enjoy coffee.";
  if (input.includes("Can I rent a tour car")) return "Yes, you can rent a tourist car from transportation companies or rental services in Thai Nguyen.";
  if (input.includes("Can I explore by bike")) return "Yes, you can explore Thai Nguyen by bike, especially around the countryside and tea villages.";
  if (input.includes("Is there a mud bath")) return "Currently, there are no mud bath services in Thai Nguyen, but you can relax in hot spring areas near tourist sites.";
  if (input.includes("Can I walk around for sightseeing")) return "Yes, Thai Nguyen has many places to explore on foot, such as around Nui Coc Lake and historical sites.";
  if (input.includes("Is there a hospital in Thai Nguyen")) return "Yes, Thai Nguyen has several hospitals like Thai Nguyen General Hospital and many smaller clinics.";
  if (input.includes("Can I find a pharmacy in Thai Nguyen")) return "Yes, there are pharmacies throughout Thai Nguyen, especially near major roads and markets.";
  if (input.includes("What is the weather like in Thai Nguyen")) return "Thai Nguyen has a temperate climate with hot summers and cold winters. The best time to visit is from September to November.";
  if (input.includes("How is the air quality in Thai Nguyen")) return "The air quality in Thai Nguyen is generally good, with less pollution compared to major cities like Hanoi.";
  if (input.includes("Is it safe to travel to Thai Nguyen")) return "Yes, Thai Nguyen is considered a safe destination for travelers with a welcoming local community.";
  if (input.includes("Are there any ancient temples in Thai Nguyen")) return "Yes, Thai Nguyen has several ancient temples like the Cau Temple and many pagodas in the surrounding areas.";
  if (input.includes("Can I go on a hiking tour in Thai Nguyen")) return "Yes, you can enjoy hiking in Thai Nguyen, especially in the mountain areas like around Nui Coc Lake and Van Son Pagoda.";
  if (input.includes("Are there any lakes to visit in Thai Nguyen")) return "Yes, besides Nui Coc Lake, Thai Nguyen has several smaller lakes and rivers perfect for sightseeing and photography.";
  if (input.includes("What is the best time to visit Thai Nguyen")) return "The best time to visit Thai Nguyen is during the autumn months, from September to November, when the weather is cool and pleasant.";
  if (input.includes("Is Thai Nguyen suitable for family trips")) return "Yes, Thai Nguyen is an ideal destination for family trips, with many attractions and outdoor activities for all ages.";
  if (input.includes("Can I visit historical sites in Thai Nguyen")) return "Yes, Thai Nguyen has many historical sites like the Viet Bac Resistance Base and other revolutionary landmarks.";
  if (input.includes("Where can I buy tea in Thai Nguyen")) return "You can buy high-quality Tan Cuong tea directly from tea shops or the Tan Cuong Tea Village.";
  if (input.includes("Is Thai Nguyen a good place for eco-tourism")) return "Yes, Thai Nguyen is great for eco-tourism, with lush green tea gardens, mountains, and natural lakes perfect for outdoor exploration.";
  if (input.includes("What is the local culture of Thai Nguyen")) return "Thai Nguyen's local culture is rich in traditions, with many ethnic minorities, historical sites, and cultural festivals.";
  if (input.includes("Can I visit tea farms in Thai Nguyen")) return "Yes, you can visit tea farms in Tan Cuong and other surrounding areas to learn about tea production and enjoy fresh tea.";
  if (input.includes("Is there a cultural center in Thai Nguyen")) return "Yes, Thai Nguyen has a cultural center where visitors can learn about the province's history, culture, and traditions.";
  if (input.includes("Are there any local festivals in Thai Nguyen")) return "Yes, Thai Nguyen celebrates various local festivals such as the Lim Festival, the Van Son Pagoda Festival, and others.";
  if (input.includes("Can I find handicrafts in Thai Nguyen")) return "Yes, you can find local handicrafts such as handwoven fabrics and wooden carvings at markets and craft stores in Thai Nguyen.";
  if (input.includes("Is there a zoo in Thai Nguyen")) return "Currently, there is no zoo in Thai Nguyen, but you can visit natural reserves and wildlife areas for a similar experience.";
  if (input.includes("Can I go fishing in Thai Nguyen")) return "Yes, fishing is a popular activity in Thai Nguyen, especially around Nui Coc Lake and nearby rivers.";
  if (input.includes("What are the main industries in Thai Nguyen")) return "The main industries in Thai Nguyen are tea production, mining, and manufacturing, including textiles and food processing.";
  if (input.includes("What is the local language in Thai Nguyen")) return "The local language in Thai Nguyen is Vietnamese, though many people in tourist areas may speak basic English.";
  if (input.includes("Is Thai Nguyen a good place for a honeymoon")) return "Yes, Thai Nguyen is a peaceful and romantic destination with scenic landscapes and many spots perfect for a honeymoon.";
  if (input.includes("Can I go boating on Nui Coc Lake")) return "Yes, you can rent a boat to enjoy the serene beauty of Nui Coc Lake and explore the surrounding islands.";
  if (input.includes("What is the transportation like in Thai Nguyen")) return "Transportation in Thai Nguyen includes buses, taxis, and personal vehicles, and it is easy to travel between major attractions.";
  if (input.includes("Is there a cinema in Thai Nguyen")) return "Yes, Thai Nguyen has a cinema where you can enjoy the latest movies in a comfortable setting.";
  if (input.includes("Are there shopping malls in Thai Nguyen")) return "Yes, Thai Nguyen has several shopping malls where you can find clothing, accessories, and local products.";
  if (input.includes("Is there a train station in Thai Nguyen")) return "Yes, Thai Nguyen has a railway station with trains connecting to Hanoi and other northern provinces.";
  if (input.includes("Is there a bus to Nui Coc Lake")) return "Yes, you can take a bus or a taxi to Nui Coc Lake, or hire a car from Thai Nguyen city center.";
  if (input.includes("Can I book a tour in Thai Nguyen")) return "Yes, there are tour operators in Thai Nguyen offering guided tours to Nui Coc Lake, tea villages, and other attractions.";
  if (input.includes("Are there any nature reserves in Thai Nguyen")) return "Yes, Thai Nguyen has several nature reserves and national parks that protect local wildlife and forests.";
  if (input.includes("Can I go kayaking in Thai Nguyen")) return "Yes, you can go kayaking on Nui Coc Lake, which offers a peaceful and scenic environment for water activities.";
  if (input.includes("Is there a bike rental in Thai Nguyen")) return "Yes, you can rent bikes from local shops or hotels to explore the province at your own pace.";
  if (input.includes("Can I visit the tea gardens in Tan Cuong")) return "Yes, you can visit the tea gardens in Tan Cuong to see how tea is grown and processed, and even enjoy fresh tea.";
  if (input.includes("What is the local economy in Thai Nguyen")) return "The economy of Thai Nguyen is based on agriculture, especially tea production, as well as manufacturing and mining industries.";
  if (input.includes("Are there any temples in Thai Nguyen")) return "Yes, Thai Nguyen has many temples and pagodas, such as the Cau Temple and many in the surrounding areas.";
  if (input.includes("Where is Thai Nguyen province located")) return "Thai Nguyen is located in the northeastern part of Vietnam, about 80 km north of Hanoi.";
  if (input.includes("How can I get to Thai Nguyen from Hanoi")) return "You can travel to Thai Nguyen by car, bus, or train. It takes around 1.5 hours from Hanoi.";
  if (input.includes("Are there any scenic routes to Thai Nguyen")) return "Yes, the road from Hanoi to Thai Nguyen passes through lush green landscapes and picturesque countryside.";
  if (input.includes("What is the best way to travel around Thai Nguyen")) return "The best way to travel around Thai Nguyen is by car, motorbike, or taxi. Public transport is also available.";
  if (input.includes("What are the main tourist attractions in Thai Nguyen")) return "Main attractions include Nui Coc Lake, Tan Cuong Tea Village, Van Son Pagoda, and the Viet Bac Resistance Base.";
  if (input.includes("Is Thai Nguyen a good place for hiking")) return "Yes, Thai Nguyen offers many hiking opportunities, especially in areas like Nui Coc Lake and surrounding mountains.";
  if (input.includes("Is there a boat tour at Nui Coc Lake")) return "Yes, you can enjoy a boat tour on Nui Coc Lake, which is a popular activity for visitors.";
  if (input.includes("What activities can I do at Nui Coc Lake")) return "You can enjoy boating, sightseeing, hiking, and visiting nearby islands at Nui Coc Lake.";
  if (input.includes("What is the significance of Nui Coc Lake")) return "Nui Coc Lake is a famous scenic spot in Thai Nguyen, known for its historical and cultural importance.";
  if (input.includes("Can I swim in Nui Coc Lake")) return "Swimming is possible in Nui Coc Lake, but it is better to check local conditions before doing so.";
  if (input.includes("Where can I try local Thai Nguyen tea")) return "You can try local Tan Cuong tea at tea shops in Thai Nguyen or visit Tan Cuong Tea Village.";
  if (input.includes("Can I buy Thai Nguyen tea as souvenirs")) return "Yes, you can buy high-quality Tan Cuong tea as souvenirs from local shops or tea villages.";
  if (input.includes("Is there a local market in Thai Nguyen")) return "Yes, Thai Nguyen has several local markets where you can buy fresh produce, local crafts, and souvenirs.";
  if (input.includes("Is there a night market in Thai Nguyen")) return "Yes, there are night markets in Thai Nguyen where you can find local street food and various goods.";
  if (input.includes("What is the local specialty of Thai Nguyen")) return "The local specialty is Tan Cuong tea, which is known for its rich flavor and high quality.";
  if (input.includes("Can I go to Thai Nguyen by train")) return "Yes, you can take a train to Thai Nguyen from Hanoi or other northern provinces.";
  if (input.includes("Is there a historical museum in Thai Nguyen")) return "Yes, Thai Nguyen has a local museum where you can learn about the province's history and culture.";
  if (input.includes("Can I visit temples and pagodas in Thai Nguyen")) return "Yes, Thai Nguyen is home to many ancient temples and pagodas, such as Van Son Pagoda and Cau Temple.";
  if (input.includes("What is the best time to visit Thai Nguyen")) return "The best time to visit Thai Nguyen is during the autumn months, from September to November, when the weather is cool and pleasant.";
  if (input.includes("What are the popular festivals in Thai Nguyen")) return "Some popular festivals in Thai Nguyen are the Lim Festival, the Van Son Pagoda Festival, and the Tết Nguyên Đán (Lunar New Year) celebrations.";
  if (input.includes("Is Thai Nguyen suitable for a cultural trip")) return "Yes, Thai Nguyen is a great destination for cultural trips, with many historical and cultural landmarks to explore.";
  if (input.includes("Can I find local crafts in Thai Nguyen")) return "Yes, you can find local crafts such as handwoven fabrics, wooden carvings, and pottery in Thai Nguyen.";
  if (input.includes("Can I learn about tea production in Thai Nguyen")) return "Yes, you can visit Tan Cuong Tea Village to learn about tea cultivation and processing.";
  if (input.includes("What is Tan Cuong Tea known for")) return "Tan Cuong Tea is known for its smooth, aromatic flavor and high quality, making it one of Vietnam's best teas.";
  if (input.includes("Is there a water park in Thai Nguyen")) return "Currently, there are no large water parks in Thai Nguyen, but you can enjoy water-related activities at Nui Coc Lake.";
  if (input.includes("Can I visit the Viet Bac Resistance Base")) return "Yes, the Viet Bac Resistance Base is an important historical site where you can learn about the Vietnamese resistance during the war.";
  if (input.includes("Where can I try local Thai Nguyen dishes")) return "You can try local Thai Nguyen dishes at restaurants and street food stalls around the city, such as bun cha, banh chung, and com lam.";
  if (input.includes("What are the famous landmarks in Thai Nguyen")) return "Famous landmarks in Thai Nguyen include Nui Coc Lake, Van Son Pagoda, Tan Cuong Tea Village, and the Viet Bac Resistance Base.";
  if (input.includes("What is the best transportation to explore Thai Nguyen")) return "The best transportation options are by car, motorbike, or taxi. You can rent a motorbike or car for more flexibility.";
  if (input.includes("Are there hotels near Nui Coc Lake")) return "Yes, there are several hotels and resorts near Nui Coc Lake offering beautiful views and convenient services.";
  if (input.includes("Can I find a guided tour in Thai Nguyen")) return "Yes, you can find guided tours that cover various attractions like Nui Coc Lake, Tan Cuong Tea Village, and historical sites.";
  if (input.includes("Can I visit tea plantations in Tan Cuong")) return "Yes, you can visit the tea plantations in Tan Cuong to explore the lush tea fields and learn about tea harvesting.";
  if (input.includes("Is Thai Nguyen good for a family vacation")) return "Yes, Thai Nguyen is a great destination for family vacations with activities suitable for all ages, including sightseeing, tea tours, and boating.";
  if (input.includes("Is there a shopping mall in Thai Nguyen")) return "Yes, there are a few shopping malls in Thai Nguyen, including Coopmart, Big C, and smaller local shops.";
  if (input.includes("What are the best restaurants in Thai Nguyen")) return "Some of the best restaurants in Thai Nguyen are Lua Moi Restaurant, Nui Coc Lake Restaurant, and the Green Tea Restaurant.";
  if (input.includes("Are there any parks for relaxation in Thai Nguyen")) return "Yes, there are several parks in Thai Nguyen, including Trung Tam Park and the peaceful areas around Nui Coc Lake.";
  if (input.includes("Can I go to a hot spring in Thai Nguyen")) return "Currently, there are no dedicated hot spring resorts in Thai Nguyen, but you can enjoy the natural hot water in some rural areas.";
  if (input.includes("Is there a place to go fishing in Thai Nguyen")) return "Yes, you can go fishing at Nui Coc Lake, rivers, and ponds around the province.";
  if (input.includes("Is Thai Nguyen a good place for eco-tourism")) return "Yes, with its natural beauty, tea gardens, and clean environment, Thai Nguyen is an excellent destination for eco-tourism.";
  if (input.includes("Can I explore the countryside in Thai Nguyen")) return "Yes, you can explore the countryside by renting a motorbike, bike, or car and visit the tea farms, mountains, and rural villages.";
  if (input.includes("Is Thai Nguyen known for its tea")) return "Yes, Thai Nguyen is famous for its high-quality tea, especially Tan Cuong tea, which is one of Vietnam's best.";
  if (input.includes("Are there any art galleries in Thai Nguyen")) return "Yes, there are a few art galleries and cultural centers where you can see local artworks and crafts.";
  if (input.includes("What is the nightlife like in Thai Nguyen")) return "The nightlife in Thai Nguyen is calm, with a few bars and cafes where you can relax after a day of sightseeing.";
  if (input.includes("Thái Nguyên có những món ăn đặc sản gì")) return "Thái Nguyên nổi tiếng với các món ăn đặc sản như bún chả, bánh chưng, cơm lam và chè Tân Cương.";
  if (input.includes("Có chỗ nào để đi chơi ở Thái Nguyên không")) return "Thái Nguyên có nhiều địa điểm du lịch hấp dẫn như Hồ Núi Cốc, Làng Chè Tân Cương và Chùa Vạn Sơn.";
  if (input.includes("Thái Nguyên có những địa điểm du lịch nào nổi tiếng")) return "Các địa điểm du lịch nổi tiếng của Thái Nguyên bao gồm Hồ Núi Cốc, Làng Chè Tân Cương, Chùa Vạn Sơn và Di tích Kháng chiến Việt Bắc.";
  if (input.includes("Làm sao để đi đến Hồ Núi Cốc")) return "Để đến Hồ Núi Cốc, bạn có thể đi xe buýt hoặc taxi từ trung tâm thành phố Thái Nguyên, mất khoảng 30-40 phút.";
  if (input.includes("Thái Nguyên có những địa danh lịch sử nào")) return "Thái Nguyên có nhiều di tích lịch sử quan trọng như Di tích Kháng chiến Việt Bắc, Chùa Vạn Sơn và những địa điểm liên quan đến kháng chiến chống Pháp.";
  if (input.includes("Có chỗ nào để mua trà ở Thái Nguyên không")) return "Bạn có thể mua trà Tân Cương nổi tiếng tại các cửa hàng trà hoặc đến trực tiếp Làng Chè Tân Cương để tham quan và mua trà.";
  if (input.includes("Thái Nguyên có những lễ hội nào nổi tiếng")) return "Thái Nguyên có nhiều lễ hội truyền thống như Lễ hội Lim, Lễ hội Chùa Vạn Sơn và Lễ hội Xuân.";
  if (input.includes("Thái Nguyên có những thắng cảnh thiên nhiên nào")) return "Thái Nguyên có những thắng cảnh thiên nhiên tuyệt đẹp như Hồ Núi Cốc, các đồi chè và những khu vực núi rừng hoang sơ.";
  if (input.includes("Thái Nguyên có những chỗ du lịch sinh thái không")) return "Có, Thái Nguyên có nhiều địa điểm du lịch sinh thái, đặc biệt là các khu vực chè Tân Cương và các khu rừng tự nhiên.";
  if (input.includes("Có thể tham gia tour du lịch ở Thái Nguyên không")) return "Có, bạn có thể tham gia các tour du lịch tham quan các địa danh nổi tiếng như Hồ Núi Cốc, Làng Chè Tân Cương và các di tích lịch sử của Thái Nguyên.";
  if (input.includes("Có dịch vụ cho thuê xe máy ở Thái Nguyên không")) return "Có, bạn có thể thuê xe máy ở các cửa hàng hoặc khách sạn tại Thái Nguyên để khám phá tỉnh.";
  if (input.includes("Thái Nguyên có sân bay không")) return "Hiện tại, Thái Nguyên không có sân bay, nhưng bạn có thể di chuyển đến Thái Nguyên bằng xe khách hoặc tàu từ Hà Nội.";
  if (input.includes("Làm sao để đi từ Hà Nội đến Thái Nguyên")) return "Bạn có thể đi từ Hà Nội đến Thái Nguyên bằng xe buýt, taxi hoặc tàu hỏa, thời gian di chuyển khoảng 1.5 - 2 giờ.";
  if (input.includes("Thái Nguyên có những khu nghỉ dưỡng nào không")) return "Thái Nguyên có một số khu nghỉ dưỡng như khu vực Hồ Núi Cốc và các khách sạn gần trung tâm thành phố.";
  if (input.includes("Thái Nguyên có những khu vực vui chơi cho trẻ em không")) return "Thái Nguyên có các công viên, khu vui chơi cho trẻ em như Trung tâm Văn hóa và các khu vực quanh Hồ Núi Cốc.";
  if (input.includes("Thái Nguyên có những di tích lịch sử gì")) return "Thái Nguyên có các di tích lịch sử như Di tích Kháng chiến Việt Bắc, Di tích Địa đạo Vĩnh Linh và các di tích cách mạng khác.";
  if (input.includes("Có thể mua quà lưu niệm ở Thái Nguyên không")) return "Bạn có thể mua quà lưu niệm như sản phẩm từ chè, các món đồ thủ công truyền thống tại các chợ và cửa hàng ở Thái Nguyên.";
  if (input.includes("Thái Nguyên có những loại trà nổi tiếng nào")) return "Trà Tân Cương là loại trà nổi tiếng nhất của Thái Nguyên, được biết đến với hương vị thơm ngon và chất lượng cao.";
  if (input.includes("Có các cửa hàng bán đồ thủ công ở Thái Nguyên không")) return "Có, bạn có thể tìm thấy các cửa hàng bán đồ thủ công như đồ gỗ, thêu, và các sản phẩm dệt may tại các chợ và cửa hàng ở Thái Nguyên.";
  if (input.includes("Thái Nguyên có những địa điểm tham quan nào cho gia đình")) return "Thái Nguyên có nhiều địa điểm thích hợp cho gia đình như Hồ Núi Cốc, các khu du lịch sinh thái và các công viên gần trung tâm.";
  if (input.includes("Thái Nguyên có các hoạt động thể thao gì")) return "Thái Nguyên có các hoạt động thể thao như đi bộ, leo núi, chèo thuyền và các trò chơi ngoài trời tại Hồ Núi Cốc.";
  if (input.includes("Thái Nguyên có trung tâm mua sắm nào không")) return "Có, bạn có thể tìm thấy các trung tâm mua sắm như Coopmart, Big C và các cửa hàng nhỏ tại Thái Nguyên.";
  if (input.includes("Có các hoạt động văn hóa ở Thái Nguyên không")) return "Có, Thái Nguyên tổ chức nhiều hoạt động văn hóa như lễ hội truyền thống, triển lãm nghệ thuật và các sự kiện âm nhạc.";
  if (input.includes("Có các điểm du lịch khám phá thiên nhiên ở Thái Nguyên không")) return "Có, bạn có thể khám phá thiên nhiên ở các khu vực chè Tân Cương, Hồ Núi Cốc và các khu rừng tự nhiên ở Thái Nguyên.";
  if (input.includes("Thái Nguyên có những món ăn đặc sản gì")) return "Thái Nguyên nổi tiếng với các món ăn đặc sản như bún chả, bánh chưng, cơm lam và chè Tân Cương.";
  if (input.includes("Có chỗ nào để đi chơi ở Thái Nguyên không")) return "Thái Nguyên có nhiều địa điểm du lịch hấp dẫn như Hồ Núi Cốc, Làng Chè Tân Cương và Chùa Vạn Sơn.";
  if (input.includes("Thái Nguyên có những địa điểm du lịch nào nổi tiếng")) return "Các địa điểm du lịch nổi tiếng của Thái Nguyên bao gồm Hồ Núi Cốc, Làng Chè Tân Cương, Chùa Vạn Sơn và Di tích Kháng chiến Việt Bắc.";
  if (input.includes("Làm sao để đi đến Hồ Núi Cốc")) return "Để đến Hồ Núi Cốc, bạn có thể đi xe buýt hoặc taxi từ trung tâm thành phố Thái Nguyên, mất khoảng 30-40 phút.";
  if (input.includes("Thái Nguyên có những địa danh lịch sử nào")) return "Thái Nguyên có nhiều di tích lịch sử quan trọng như Di tích Kháng chiến Việt Bắc, Chùa Vạn Sơn và những địa điểm liên quan đến kháng chiến chống Pháp.";
  if (input.includes("Có chỗ nào để mua trà ở Thái Nguyên không")) return "Bạn có thể mua trà Tân Cương nổi tiếng tại các cửa hàng trà hoặc đến trực tiếp Làng Chè Tân Cương để tham quan và mua trà.";
  if (input.includes("Thái Nguyên có những lễ hội nào nổi tiếng")) return "Thái Nguyên có nhiều lễ hội truyền thống như Lễ hội Lim, Lễ hội Chùa Vạn Sơn và Lễ hội Xuân.";
  if (input.includes("Thái Nguyên có những thắng cảnh thiên nhiên nào")) return "Thái Nguyên có những thắng cảnh thiên nhiên tuyệt đẹp như Hồ Núi Cốc, các đồi chè và những khu vực núi rừng hoang sơ.";
  if (input.includes("Thái Nguyên có những chỗ du lịch sinh thái không")) return "Có, Thái Nguyên có nhiều địa điểm du lịch sinh thái, đặc biệt là các khu vực chè Tân Cương và các khu rừng tự nhiên.";
  if (input.includes("Có thể tham gia tour du lịch ở Thái Nguyên không")) return "Có, bạn có thể tham gia các tour du lịch tham quan các địa danh nổi tiếng như Hồ Núi Cốc, Làng Chè Tân Cương và các di tích lịch sử của Thái Nguyên.";
  if (input.includes("Có dịch vụ cho thuê xe máy ở Thái Nguyên không")) return "Có, bạn có thể thuê xe máy ở các cửa hàng hoặc khách sạn tại Thái Nguyên để khám phá tỉnh.";
  if (input.includes("Thái Nguyên có sân bay không")) return "Hiện tại, Thái Nguyên không có sân bay, nhưng bạn có thể di chuyển đến Thái Nguyên bằng xe khách hoặc tàu từ Hà Nội.";
  if (input.includes("Làm sao để đi từ Hà Nội đến Thái Nguyên")) return "Bạn có thể đi từ Hà Nội đến Thái Nguyên bằng xe buýt, taxi hoặc tàu hỏa, thời gian di chuyển khoảng 1.5 - 2 giờ.";
  if (input.includes("Thái Nguyên có những khu nghỉ dưỡng nào không")) return "Thái Nguyên có một số khu nghỉ dưỡng như khu vực Hồ Núi Cốc và các khách sạn gần trung tâm thành phố.";
  if (input.includes("Thái Nguyên có những khu vực vui chơi cho trẻ em không")) return "Thái Nguyên có các công viên, khu vui chơi cho trẻ em như Trung tâm Văn hóa và các khu vực quanh Hồ Núi Cốc.";
  if (input.includes("Thái Nguyên có những di tích lịch sử gì")) return "Thái Nguyên có các di tích lịch sử như Di tích Kháng chiến Việt Bắc, Di tích Địa đạo Vĩnh Linh và các di tích cách mạng khác.";
  if (input.includes("Có thể mua quà lưu niệm ở Thái Nguyên không")) return "Bạn có thể mua quà lưu niệm như sản phẩm từ chè, các món đồ thủ công truyền thống tại các chợ và cửa hàng ở Thái Nguyên.";
  if (input.includes("Thái Nguyên có những loại trà nổi tiếng nào")) return "Trà Tân Cương là loại trà nổi tiếng nhất của Thái Nguyên, được biết đến với hương vị thơm ngon và chất lượng cao.";
  if (input.includes("Có các cửa hàng bán đồ thủ công ở Thái Nguyên không")) return "Có, bạn có thể tìm thấy các cửa hàng bán đồ thủ công như đồ gỗ, thêu, và các sản phẩm dệt may tại các chợ và cửa hàng ở Thái Nguyên.";
  if (input.includes("Thái Nguyên có những địa điểm tham quan nào cho gia đình")) return "Thái Nguyên có nhiều địa điểm thích hợp cho gia đình như Hồ Núi Cốc, các khu du lịch sinh thái và các công viên gần trung tâm.";
  if (input.includes("Thái Nguyên có các hoạt động thể thao gì")) return "Thái Nguyên có các hoạt động thể thao như đi bộ, leo núi, chèo thuyền và các trò chơi ngoài trời tại Hồ Núi Cốc.";
  if (input.includes("Thái Nguyên có trung tâm mua sắm nào không")) return "Có, bạn có thể tìm thấy các trung tâm mua sắm như Coopmart, Big C và các cửa hàng nhỏ tại Thái Nguyên.";
  if (input.includes("Có các hoạt động văn hóa ở Thái Nguyên không")) return "Có, Thái Nguyên tổ chức nhiều hoạt động văn hóa như lễ hội truyền thống, triển lãm nghệ thuật và các sự kiện âm nhạc.";
  if (input.includes("Có các điểm du lịch khám phá thiên nhiên ở Thái Nguyên không")) return "Có, bạn có thể khám phá thiên nhiên ở các khu vực chè Tân Cương, Hồ Núi Cốc và các khu rừng tự nhiên ở Thái Nguyên.";
  if (input.includes("Thái Nguyên có những chỗ tham quan lịch sử không")) return "Có, các di tích lịch sử nổi tiếng ở Thái Nguyên bao gồm Di tích Kháng chiến Việt Bắc, Địa đạo Vĩnh Linh và các di tích chiến tranh khác.";
  if (input.includes("Có thể đi du lịch Thái Nguyên vào mùa nào trong năm")) return "Thái Nguyên thích hợp để du lịch vào mùa thu, từ tháng 9 đến tháng 11, khi thời tiết mát mẻ và dễ chịu.";
  if (input.includes("Thái Nguyên có các di tích cách mạng nào không")) return "Thái Nguyên có Di tích Kháng chiến Việt Bắc, nơi ghi dấu nhiều sự kiện quan trọng trong kháng chiến chống Pháp.";
  if (input.includes("Có các làng nghề truyền thống nào ở Thái Nguyên không")) return "Thái Nguyên có các làng nghề truyền thống như làng nghề dệt, làng làm đồ thủ công và làng làm gốm.";
  if (input.includes("Có thể tham gia các hoạt động nông nghiệp ở Thái Nguyên không")) return "Có, bạn có thể tham gia các hoạt động nông nghiệp như tham quan các đồn điền chè Tân Cương, trồng cây và thu hoạch chè.";
  if (input.includes("Thái Nguyên có những đặc sản nào để mua làm quà")) return "Các đặc sản của Thái Nguyên gồm chè Tân Cương, cơm lam, bánh chưng và các sản phẩm thủ công như đồ gỗ và dệt may.";
  if (input.includes("Có thể khám phá những điểm di tích chiến tranh ở Thái Nguyên không")) return "Có, bạn có thể tham quan các di tích chiến tranh như Địa đạo Vĩnh Linh, khu Di tích Kháng chiến Việt Bắc, và các bảo tàng chiến tranh.";
  if (input.includes("Có thể đến Thái Nguyên bằng xe buýt không")) return "Có, có nhiều chuyến xe buýt từ Hà Nội và các tỉnh lân cận đến Thái Nguyên.";
  if (input.includes("Có thể tham gia tour nông nghiệp ở Thái Nguyên không")) return "Có, bạn có thể tham gia các tour nông nghiệp tham quan các đồn điền chè Tân Cương và học hỏi về cách sản xuất trà.";
  if (input.includes("Có các hoạt động mạo hiểm ở Thái Nguyên không")) return "Có, bạn có thể tham gia các hoạt động mạo hiểm như leo núi, đi bộ đường dài và chèo thuyền tại Hồ Núi Cốc.";
  if (input.includes("Thái Nguyên có các khu du lịch nào nổi bật trong mùa hè")) return "Trong mùa hè, các khu du lịch như Hồ Núi Cốc, các khu vực chè Tân Cương và các công viên giải trí tại Thái Nguyên rất phổ biến.";
  if (input.includes("Thái Nguyên có những cửa hàng địa phương nào bán quà lưu niệm")) return "Bạn có thể tìm thấy các cửa hàng địa phương bán quà lưu niệm tại các chợ hoặc các khu du lịch như Hồ Núi Cốc và Làng Chè Tân Cương.";
  if (input.includes("Thái Nguyên có những địa điểm đẹp để chụp ảnh không")) return "Thái Nguyên có nhiều địa điểm tuyệt vời để chụp ảnh, đặc biệt là Hồ Núi Cốc, Làng Chè Tân Cương và các khu rừng tự nhiên.";
  if (input.includes("Khách sạn nào gần Hồ Núi Cốc")) return "Bạn có thể ở Khách sạn Hồ Núi Cốc Plaza hoặc các nhà nghỉ quanh khu du lịch.";
  if (input.includes("Có homestay nào ở Thái Nguyên không")) return "Có, bạn có thể tìm các homestay tại Làng Chè Tân Cương hoặc gần khu sinh thái.";
  if (input.includes("Giá phòng khách sạn ở Thái Nguyên bao nhiêu")) return "Giá phòng dao động từ 300.000 đến 1.000.000 đồng tùy theo loại khách sạn.";
  if (input.includes("Từ Hà Nội đến Thái Nguyên bao xa")) return "Từ Hà Nội đến Thái Nguyên khoảng 80km.";
  if (input.includes("Đi xe khách đến Thái Nguyên thế nào")) return "Bạn có thể bắt xe tại bến Mỹ Đình, Gia Lâm hoặc Yên Nghĩa.";
  if (input.includes("Đường đến Làng Chè Tân Cương")) return "Bạn đi theo QL3 rồi rẽ vào đường Tân Cương, khoảng 10km từ trung tâm TP.";
  if (input.includes("Nên ăn gì khi đến Thái Nguyên")) return "Bạn nên thử chè Tân Cương, bún cá, cơm lam và bánh chưng Bờ Đậu.";
  if (input.includes("Có quán ăn ngon ở TP Thái Nguyên không")) return "Bạn có thể thử các quán ăn đặc sản như Quán Mộc, Trà Thái, hay Hương Quê.";
  if (input.includes("Chè Tân Cương có gì đặc biệt")) return "Chè Tân Cương có hương thơm dịu nhẹ, vị chát ngọt và hậu vị thanh.";
  if (input.includes("Mua trà Thái Nguyên ở đâu")) return "Bạn có thể đến chợ Thái, siêu thị Coopmart hoặc các cơ sở trà tại Tân Cương.";
  if (input.includes("Đặc sản Thái Nguyên làm quà")) return "Trà Tân Cương, bánh chưng Bờ Đậu, mứt gừng, măng rừng là những món quà phổ biến.";
  if (input.includes("Đại học nổi tiếng ở Thái Nguyên")) return "Đại học Thái Nguyên là trung tâm giáo dục lớn với nhiều trường thành viên.";
  if (input.includes("Có bệnh viện lớn nào ở Thái Nguyên")) return "Có Bệnh viện Trung ương Thái Nguyên, Bệnh viện A và các phòng khám tư nhân.";
  if (input.includes("Tôi cần tìm UBND tỉnh Thái Nguyên")) return "UBND tỉnh nằm tại số 18, đường Nha Trang, TP Thái Nguyên.";
  if (input.includes("Có gì chơi không")) return "Có rất nhiều điểm đến thú vị như Hồ Núi Cốc, Làng Chè Tân Cương, đồi thông Phú Bình.";
  if (input.includes("Tôi nên đi đâu khi đến Thái Nguyên")) return "Bạn nên bắt đầu với Hồ Núi Cốc, sau đó khám phá chè Tân Cương và các di tích lịch sử.";
  if (input.includes("Có tour du lịch trong ngày không")) return "Có rất nhiều tour du lịch 1 ngày ở Thái Nguyên khởi hành từ trung tâm thành phố.";
                                                
  return "Mình chưa hiểu câu hỏi, bạn có thể hỏi lại nhé!";
}

function speak(text) {
  if ('speechSynthesis' in window) {
    const msg = new SpeechSynthesisUtterance(text);
    msg.lang = 'vi-VN';
    speechSynthesis.speak(msg);
  } else {
    alert("Trình duyệt của bạn không hỗ trợ giọng nói.");
  }
}

